import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'
import React from "react"
import GIF from '../public/speen.gif'
import Ghost from '../public/duskull.gif'




const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  console.log(data);
  const [information, setInformation] = useState ([...data])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <Link href="about">About</Link>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src={Ghost}
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={100}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src={GIF}
            width={400}
            height={400}
            priority
            />
        </div>

        <div className={styles.grid}>
          <div className='Business'>Business Degrees:</div>
          {
            information && information.map((info, index) => {
              if(info.department === "Business") {
                return(
                  <Card key={index} degree={info.degree} colour="purple" font="15px"/>
                )
              }

              
            })
            
          }

                  <div className='Computing'>Computing Degrees:</div>
          {
            information && information.map((info, index) => {
              if(info.department === "Computing") {
                return(
                  <Card key={index} degree={info.degree} colour="purple" font="15px"/>
                )
              }
              
            })
          }


        </div>


             

          
      </main>
    </>
  )
}
